/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bibliotecadigital.presentation.desktop.views;

import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author jesus
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        panelElementos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnGestionarAutores = new javax.swing.JButton();
        btnGestionarMateriales = new javax.swing.JButton();
        btnGestionarUsuarios = new javax.swing.JButton();
        btnGestionarPrestamos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Digital");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));

        panelElementos.setLayout(new java.awt.GridLayout(1, 0));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 150)); // NOI18N
        lblNombre.setText("Biblioteca Digital");
        panelElementos.add(lblNombre);

        panel.add(panelElementos);

        panelBotones.setLayout(new java.awt.GridLayout(1, 0));

        btnGestionarAutores.setBackground(new java.awt.Color(0, 51, 255));
        btnGestionarAutores.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnGestionarAutores.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarAutores.setText("Gestionar Autores");
        panelBotones.add(btnGestionarAutores);

        btnGestionarMateriales.setBackground(new java.awt.Color(0, 51, 255));
        btnGestionarMateriales.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnGestionarMateriales.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarMateriales.setText("Gestionar Materiales");
        panelBotones.add(btnGestionarMateriales);

        btnGestionarUsuarios.setBackground(new java.awt.Color(0, 51, 255));
        btnGestionarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnGestionarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarUsuarios.setText("Gestionar Usuarios");
        panelBotones.add(btnGestionarUsuarios);

        btnGestionarPrestamos.setBackground(new java.awt.Color(0, 51, 255));
        btnGestionarPrestamos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnGestionarPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarPrestamos.setText("Gestionar Préstamos");
        panelBotones.add(btnGestionarPrestamos);

        panel.add(panelBotones);

        getContentPane().add(panel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Métodos para que el controlador añada los listeners
    public void addGestionarAutoresListener(ActionListener listener) {
        btnGestionarAutores.addActionListener(listener);
    }
    public void addGestionarMaterialesListener(ActionListener listener) {
        btnGestionarMateriales.addActionListener(listener);
    }
    public void addGestionarUsuariosListener(ActionListener listener) {
        btnGestionarUsuarios.addActionListener(listener);
    }
    public void addGestionarPrestamosListener(ActionListener listener) {
        btnGestionarPrestamos.addActionListener(listener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionarAutores;
    private javax.swing.JButton btnGestionarMateriales;
    private javax.swing.JButton btnGestionarPrestamos;
    private javax.swing.JButton btnGestionarUsuarios;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelElementos;
    // End of variables declaration//GEN-END:variables
}
